// Generated by CoffeeScript 1.10.0
(function() {
  var Compiler, StylCompiler, de_res, fs, rework_calc, rework_color, rework_colors, rework_import, rework_inherit, rework_shade, rework_variant, styl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  fs = require('fs');

  styl = require('styl');

  rework_calc = require('rework-calc');

  rework_color = require('rework-color-function');

  rework_colors = require('rework-plugin-colors');

  rework_inherit = require('rework-inherit');

  rework_variant = require('rework-variant');

  rework_shade = require('rework-shade');

  rework_import = require('rework-import');

  Compiler = require('metaserve/lib/compiler');

  de_res = function(n) {
    return Math.floor(n / 1000) * 1000;
  };

  StylCompiler = (function(superClass) {
    extend(StylCompiler, superClass);

    function StylCompiler() {
      return StylCompiler.__super__.constructor.apply(this, arguments);
    }

    StylCompiler.prototype.default_options = {
      import_dir: './static/css',
      ext: 'sass',
      vars: {}
    };

    StylCompiler.prototype.compile = function(sass_filename) {
      var options;
      options = this.options;
      return function(req, res, next) {
        var compiled, pre_transformer, sass_src, transformer, variant;
        variant = rework_variant(options.vars);
        pre_transformer = function(sass_src) {
          return styl(sass_src, {
            whitespace: true
          }).use(rework_import({
            path: options.import_dir,
            transform: pre_transformer
          })).toString();
        };
        transformer = function(sass_src) {
          return styl(pre_transformer(sass_src)).use(rework_inherit()).use(variant).use(rework_calc).use(rework_colors()).use(rework_color).toString();
        };
        sass_src = fs.readFileSync(sass_filename).toString();
        compiled = transformer(sass_src);
        res.setHeader('Content-Type', 'text/css');
        return res.end(compiled);
      };
    };

    return StylCompiler;

  })(Compiler);

  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    return new StylCompiler(options);
  };

}).call(this);
